/*
 * Generated by tools/gen_font.py - do not edit.
 */

#ifndef FONT_DATA_H
#define FONT_DATA_H

#include <stdint.h>

#define FONT_FIRST_CHAR 32
#define FONT_LAST_CHAR  126
#define FONT_GLYPH_COUNT 95

extern const uint8_t  font_tiles[3040];
extern const uint16_t font_palette[16];

#endif
