/* Generated by compiler/modes.py from engine_settings.json - do not edit. */
#ifndef MODE_SETTINGS_H
#define MODE_SETTINGS_H

#define SCENE_MODE_TOPDOWN      0
#define SCENE_MODE_PLATFORM     1
#define SCENE_MODE_ADVENTURE    2
#define SCENE_MODE_SHMUP        3
#define SCENE_MODE_POINTNCLICK  4
#define SCENE_MODE_LOGO         5

#define MS_TD_SPEED               0   /* Walk speed (speed) */
#define MS_TD_GRID                1   /* Movement grid (choice) */
#define MS_TD_DIAGONAL            2   /* Diagonal movement (bool) */
#define MS_TD_RUN                 3   /* Enable running (bool) */
#define MS_TD_RUN_BUTTON          4   /* Run button (button) */
#define MS_TD_RUN_SPEED           5   /* Run speed (speed) */
#define MS_TD_INTERACT            6   /* Interact button (button) */
#define MS_PL_WALK_VEL            7   /* Walk speed (speed) */
#define MS_PL_WALK_ACC            8   /* Walk acceleration (accel) */
#define MS_PL_TURN_ACC            9   /* Turn acceleration (accel) */
#define MS_PL_DEC                 10   /* Deceleration (accel) */
#define MS_PL_AIR_CONTROL         11   /* Air control (bool) */
#define MS_PL_AIR_DEC             12   /* Air deceleration (accel) */
#define MS_PL_CROUCH              13   /* Crouch (hold Down) (bool) */
#define MS_PL_RUN                 14   /* Enable running (bool) */
#define MS_PL_RUN_BUTTON          15   /* Run button (button) */
#define MS_PL_RUN_VEL             16   /* Run speed (speed) */
#define MS_PL_RUN_ACC             17   /* Run acceleration (accel) */
#define MS_PL_GRAV                18   /* Gravity (accel) */
#define MS_PL_MAX_FALL            19   /* Max fall speed (speed) */
#define MS_PL_JUMP                20   /* Enable jumping (bool) */
#define MS_PL_JUMP_BUTTON         21   /* Jump button (button) */
#define MS_PL_JUMP_VEL            22   /* Jump speed (speed) */
#define MS_PL_HOLD_GRAV           23   /* Gravity while holding jump (accel) */
#define MS_PL_HOLD_FRAMES         24   /* Hold frames (frames) */
#define MS_PL_COYOTE              25   /* Coyote time (frames) (frames) */
#define MS_PL_JUMP_BUFFER         26   /* Jump buffer (frames) (frames) */
#define MS_PL_EXTRA_JUMPS         27   /* Air jumps (double jump) (count) */
#define MS_PL_EXTRA_JUMP_VEL      28   /* Air jump speed (speed) */
#define MS_PL_WALL_JUMP           29   /* Wall jump (bool) */
#define MS_PL_WALL_JUMPS_MAX      30   /* Wall jumps before landing (0 = no limit) (count) */
#define MS_PL_WALL_KICK           31   /* Wall kick speed (speed) */
#define MS_PL_WALL_SLIDE          32   /* Wall slide (bool) */
#define MS_PL_WALL_SLIDE_VEL      33   /* Wall slide speed (speed) */
#define MS_PL_DROP_THROUGH        34   /* Drop through platforms (bool) */
#define MS_PL_LADDERS             35   /* Ladders (bool) */
#define MS_PL_CLIMB_VEL           36   /* Climb speed (speed) */
#define MS_PL_DASH                37   /* Dash (bool) */
#define MS_PL_DASH_INPUT          38   /* Dash input (choice) */
#define MS_PL_DASH_DIST           39   /* Dash distance (px) (pixels) */
#define MS_PL_DASH_FRAMES         40   /* Dash time (frames) (frames) */
#define MS_PL_DASH_READY          41   /* Cooldown (frames) (frames) */
#define MS_PL_DASH_AIR            42   /* Dash in the air (bool) */
#define MS_PL_FLOAT               43   /* Float (hold Jump while falling) (bool) */
#define MS_PL_FLOAT_VEL           44   /* Float fall speed (speed) */
#define MS_PL_KNOCKBACK           45   /* Knockback (bool) */
#define MS_PL_KB_VEL_X            46   /* Knockback speed X (speed) */
#define MS_PL_KB_VEL_Y            47   /* Knockback speed Y (speed) */
#define MS_PL_KB_FRAMES           48   /* Knockback time (frames) (frames) */
#define MS_PL_LOOK_AHEAD          49   /* Camera look-ahead (px) (pixels) */
#define MS_PL_INTERACT            50   /* Interact button (button) */
#define MS_AD_EIGHT_WAY           51   /* 8-way movement (bool) */
#define MS_AD_FACE_HORIZONTAL     52   /* Only face left/right (bool) */
#define MS_AD_WALK_VEL            53   /* Walk speed (speed) */
#define MS_AD_WALK_ACC            54   /* Acceleration (accel) */
#define MS_AD_DEC                 55   /* Deceleration (accel) */
#define MS_AD_RUN                 56   /* Enable running (bool) */
#define MS_AD_RUN_BUTTON          57   /* Run button (button) */
#define MS_AD_RUN_VEL             58   /* Run speed (speed) */
#define MS_AD_DASH                59   /* Dash (bool) */
#define MS_AD_DASH_INPUT          60   /* Dash input (choice) */
#define MS_AD_DASH_DIST           61   /* Dash distance (px) (pixels) */
#define MS_AD_DASH_FRAMES         62   /* Dash time (frames) (frames) */
#define MS_AD_DASH_READY          63   /* Cooldown (frames) (frames) */
#define MS_AD_PUSH                64   /* Push actors (bool) */
#define MS_AD_PUSH_DELAY          65   /* Push delay (frames) (frames) */
#define MS_AD_KNOCKBACK           66   /* Knockback (bool) */
#define MS_AD_KB_VEL              67   /* Knockback speed (speed) */
#define MS_AD_KB_FRAMES           68   /* Knockback time (frames) (frames) */
#define MS_AD_INTERACT            69   /* Interact button (button) */
#define MS_SH_SCROLL_SPEED        70   /* Scroll speed (speed) */
#define MS_SH_PLAYER_SPEED        71   /* Player speed (speed) */
#define MS_SH_LOCK_PERPENDICULAR  72   /* Only move across the scroll (bool) */
#define MS_SH_TRIGGERS_ON_SCREEN  73   /* Triggers fire when they scroll on screen (bool) */
#define MS_SH_WALL_HIT_GROUP      74   /* Hitting a wall counts as a hit from group (choice) */
#define MS_PC_SPEED               75   /* Cursor speed (speed) */
#define MS_PC_INTERACT            76   /* Click button (button) */
#define MS_HIT_INVINCIBLE         77   /* Invincible after a hit (frames) (frames) */
#define MS_DAMAGE_TILE_GROUP      78   /* Damage tiles hit as group (choice) */

#define MS_COUNT 79

#endif
