/*
 * Generated by compiler/build_project.py from engine/data/player.png
 * (do not edit by hand - change player.png and rebuild instead)
 */

#ifndef PLAYER_GRAPHICS_H
#define PLAYER_GRAPHICS_H

#include <stdint.h>

#define PLAYER_FRAME_COUNT 8
#define PLAYER_FRAME_SIZE 128

extern const uint8_t player_graphics[];
extern const uint16_t player_palette[16];
extern const uint32_t player_frame_offsets[8];

#endif
