/*
 * Generated by compiler/build_project.py - do not edit.
 */

#ifndef SCENES_DATA_H
#define SCENES_DATA_H

#include "scene.h"

#define SCENE_COUNT       4
#define SCENE_START       (&scene_town)
#define SPRITE_COUNT      1
#define ITEM_COUNT        1

extern const SceneDef scene_house_inside;
extern const SceneDef scene_testmap;
extern const SceneDef scene_teststream;
extern const SceneDef scene_town;

extern const SceneDef *const scenes[SCENE_COUNT];
extern const SpriteDef       sprite_defs[SPRITE_COUNT];
extern const uint8_t         player_sprite_index;
extern const char *const      item_names[];

#endif
