/*
 * Generated by compiler/build_project.py - do not edit.
 */

#ifndef SCENES_DATA_H
#define SCENES_DATA_H

#include "scene.h"

#define SCENE_COUNT       1
#define SCENE_START       (&scene_start)
#define NPC_SPRITE_COUNT  1
#define ITEM_COUNT        0

extern const SceneDef scene_start;

extern const SceneDef *const scenes[SCENE_COUNT];
extern const NpcSpriteDef    npc_sprites[NPC_SPRITE_COUNT];
extern const PlayerSpriteDef player_sprite_def;
extern const char *const      item_names[];

#endif
