"""
Build a Shimmer Engine project into a .gba, start to finish, without make:

    python compiler/build_rom.py examples/demo

1. Runs the project compiler (build_project.py) into a work folder.
2. Compiles the engine's C sources and the generated data with devkitARM's
   gcc (same flags as engine/Makefile), reusing object files that are
   still up to date.
3. Links, converts to a ROM and fixes its header (gbafix).

Only devkitARM, libgba and gbafix are needed - no make, bash or WSL, so the
packaged editor can ship this (frozen with PyInstaller) plus a devkitARM
folder and build on plain Windows.

Paths (all optional):
    --engine DIR      the engine folder (default: ../engine next to this file)
    --devkitpro DIR   devkitPro root (default: $DEVKITPRO, else /opt/devkitpro)
    --work DIR        where generated files and objects go
                      (default: <project>/build/rom)
    --out FILE        the ROM to write (default: <project>/ROM/<name>.gba)
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import build_project

# engine/Makefile's flags.
ARCH = ["-mthumb", "-mthumb-interwork"]
CFLAGS = ["-g", "-Wall", "-O2", "-mcpu=arm7tdmi", "-mtune=arm7tdmi", *ARCH]
# Generated by build_project.py / uge.py into the work folder; the copies
# in engine/data (if any) are stale leftovers and must not be used.
GENERATED = {"scenes_data.c", "scenes_data.h", "uge_songs.c", "uge_songs.h", "ui_data.c"}


class RomBuildError(Exception):
    pass


def log(msg):
    print(msg, flush=True)


def tool(devkitpro, *parts):
    p = Path(devkitpro, *parts)
    if sys.platform == "win32" and not p.suffix:
        p = p.with_suffix(".exe")
    if not p.exists():
        raise RomBuildError(f"Missing build tool: {p}")
    return str(p)


def run(cmd, cwd=None):
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    out = (r.stdout + r.stderr).strip()
    if r.returncode != 0:
        raise RomBuildError(out or f"{Path(cmd[0]).name} failed (exit code {r.returncode})")
    return out


def deps_of(dfile):
    """Files an object depends on, from gcc's -MMD output (its first rule,
    "obj.o: a.c b.h ..."; spaces in paths are escaped as "\\ ")."""
    try:
        text = dfile.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None
    rule = text.replace("\\\n", " ").split("\n", 1)[0]
    # ": " ends the target; a drive letter's colon is never followed by a space.
    if ": " not in rule:
        return None
    body = rule.split(": ", 1)[1]
    return [p.replace("\\ ", " ") for p in re.split(r"(?<!\\) +", body.strip()) if p]


def up_to_date(obj, dfile, flags_key, stamp):
    if not obj.exists() or not stamp.exists() or stamp.read_text() != flags_key:
        return False
    deps = deps_of(dfile)
    if not deps:
        return False
    t = obj.stat().st_mtime
    for d in deps:
        try:
            if Path(d).stat().st_mtime > t:
                return False
        except OSError:
            return False
    return True


def rom_title(name):
    t = re.sub(r"[^A-Z0-9 ]", "", name.upper()).strip()
    return (t or "SHIMMER")[:12]


def build_rom(project, engine, devkitpro, work, out):
    project = project.resolve()
    engine = engine.resolve()
    data = work / "data"
    objdir = work / "obj"
    data.mkdir(parents=True, exist_ok=True)
    objdir.mkdir(parents=True, exist_ok=True)

    # 1. Project -> C data.
    log(f"Building {project.name}")
    build_project.DEFAULT_PLAYER_PNG = engine / "data" / "player.png"
    build_project.DEFAULT_UI_DIR = engine / "data" / "ui"
    try:
        build_project.build(project, data)
    except build_project.BuildError as e:
        raise RomBuildError(str(e)) from None

    # Static data that lives with the engine (fonts...).
    for f in (engine / "data").iterdir():
        if f.suffix in (".c", ".h") and f.name not in GENERATED:
            dest = data / f.name
            if not dest.exists() or dest.read_bytes() != f.read_bytes():
                shutil.copyfile(f, dest)
    # 2. Compile.
    gcc = tool(devkitpro, "devkitARM", "bin", "arm-none-eabi-gcc")
    objcopy = tool(devkitpro, "devkitARM", "bin", "arm-none-eabi-objcopy")
    gbafix = tool(devkitpro, "tools", "bin", "gbafix")
    libgba = Path(devkitpro) / "libgba"
    includes = ["-iquote", str(engine / "include"), "-iquote", str(data), "-I", str(libgba / "include"), "-I", str(data)]
    flags = CFLAGS + includes
    flags_key = json.dumps([gcc, flags])

    sources = sorted((engine / "source").glob("*.c")) + sorted(data.glob("*.c"))
    names = [s.stem for s in sources]
    if len(set(names)) != len(names):
        raise RomBuildError("Two source files share a name: " + ", ".join(sorted(n for n in names if names.count(n) > 1)))

    def compile_one(src):
        obj = objdir / (src.stem + ".o")
        dfile = objdir / (src.stem + ".d")
        stamp = objdir / (src.stem + ".flags")
        if up_to_date(obj, dfile, flags_key, stamp):
            return None
        run([gcc, "-MMD", "-MP", "-MF", str(dfile), *flags, "-c", str(src), "-o", str(obj)])
        stamp.write_text(flags_key)
        return src.name

    with ThreadPoolExecutor(max_workers=max(1, (os.cpu_count() or 2))) as pool:
        try:
            for name in pool.map(compile_one, sources):
                if name:
                    log(f"  compiled {name}")
        except RomBuildError as e:
            raise RomBuildError(f"The engine didn't compile:\n{e}") from None

    # Objects left over from sources that no longer exist.
    live = {s.stem for s in sources}
    for o in objdir.glob("*.o"):
        if o.stem not in live:
            o.unlink()

    # 3. Link and make the ROM.
    elf = work / "game.elf"
    gba = work / "game.gba"
    objs = [str(objdir / (s.stem + ".o")) for s in sources]
    run([gcc, "-g", *ARCH, f"-Wl,-Map,{work / 'game.map'}", "-specs=gba.specs", *objs,
         "-L", str(libgba / "lib"), "-lgba", "-o", str(elf)])
    run([objcopy, "-O", "binary", str(elf), str(gba)])
    run([gbafix, str(gba), f"-t{rom_title(project.name)}", "-c0000", "-m00"])

    out.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(gba, out)
    shutil.copyfile(elf, out.with_suffix(".elf"))
    log(f"ROM: {out}")
    return out


def main():
    here = Path(__file__).resolve().parent
    ap = argparse.ArgumentParser(description="Build a Shimmer Engine project into a .gba.")
    ap.add_argument("project", type=Path)
    ap.add_argument("--engine", type=Path, default=here.parent / "engine")
    ap.add_argument("--devkitpro", type=Path, default=Path(os.environ.get("DEVKITPRO") or "/opt/devkitpro"))
    ap.add_argument("--work", type=Path)
    ap.add_argument("--out", type=Path)
    args = ap.parse_args()

    project = args.project.resolve()
    work = (args.work or project / "build" / "rom").resolve()
    out = (args.out or project / "ROM" / (project.name + ".gba")).resolve()
    try:
        build_rom(project, args.engine, args.devkitpro, work, out)
    except RomBuildError as e:
        print(f"ERROR: {e}", file=sys.stderr, flush=True)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
