"""
Video cutscenes -> cutscenes_data.c + cutscenes_bin.s (engine/source/cutscene.c).

The editor's Cutscenes tab converts a video into, per cutscene:

    <project>/assets/cutscenes/<name>.cut   the frames (format: engine/include/cutscene.h)
    <project>/assets/cutscenes/<name>.raw   its sound: signed 8-bit mono at
                                            wav.RATE (optional)
    <project>/assets/cutscenes/<name>.json  the settings it was made with
                                            (editor only)

The .cut and .raw files go into the ROM unchanged via the assembler's
.incbin (no giant C arrays); the sound becomes an extra wav_sounds[] entry
after the project's own WAVs.
"""

from pathlib import Path

PAD = 512   # silence after a sound, as compiler/wav.py adds


class CutsceneError(Exception):
    pass


def cutscene_files(cutscenes_dir):
    """[(name, cut_path, raw_path or None)] sorted by name."""
    d = Path(cutscenes_dir)
    if not d.is_dir():
        return []
    out = []
    for p in sorted(d.glob("*.cut"), key=lambda p: p.name.lower()):
        raw = p.with_suffix(".raw")
        out.append((p.stem, p, raw if raw.exists() else None))
    return out


def check_cut(path):
    """Header sanity check; returns (frames, fps, mode)."""
    data = path.read_bytes()[:12]
    if len(data) < 12 or data[:4] != b"SHCV":
        raise CutsceneError(f"{path.name} isn't a Shimmer cutscene - convert the video again in the Cutscenes tab.")
    version = data[4] | (data[5] << 8)
    if version != 1:
        raise CutsceneError(f"{path.name} was made by a newer Shimmer Engine (format {version}).")
    frames = data[8] | (data[9] << 8)
    return frames, data[7], data[6]


def _asm_path(p):
    return str(Path(p).resolve().as_posix()).replace('"', '\\"')


def build_cutscenes(cutscenes_dir, out_dir, first_sound_index):
    """Write cutscenes_bin.s/.c. Returns (names, extra_sounds) where
    extra_sounds is [(name, ident, length)] for compiler/wav.py to add to
    wav_sounds[] starting at first_sound_index."""
    files = cutscene_files(cutscenes_dir)
    asm = ["/* Generated by compiler/cutscenes.py - do not edit. */", "    .section .rodata"]
    c = ["/* Generated by compiler/cutscenes.py - do not edit. */", "#include <stdint.h>", "", '#include "cutscene.h"', ""]
    rows = []
    extra = []
    for i, (name, cut, raw) in enumerate(files):
        check_cut(cut)
        vid = f"cutscene_{i}_video"
        asm += ["    .balign 4", f"    .global {vid}", f"{vid}:", f'    .incbin "{_asm_path(cut)}"']
        c.append(f"extern const uint8_t {vid}[];   /* {name} */")
        sound = -1
        if raw is not None and raw.stat().st_size > 0:
            aud = f"cutscene_{i}_audio"
            asm += ["    .balign 4", f"    .global {aud}", f"{aud}:", f'    .incbin "{_asm_path(raw)}"', f"    .space {PAD}"]
            sound = first_sound_index + len(extra)
            extra.append((f"{name} (cutscene)", aud, raw.stat().st_size))
        rows.append(f"    {{ {vid}, {sound} }},   /* {name} */")
    c.append("")
    if rows:
        c.append(f"const CutsceneDef cutscenes[{len(rows)}] = {{")
        c += rows
        c.append("};")
    else:
        c.append("const CutsceneDef cutscenes[1] = { { 0, -1 } };")
    c.append(f"const uint16_t cutscene_count = {len(rows)};")

    out = Path(out_dir)
    for fname, text in (("cutscenes_bin.s", "\n".join(asm) + "\n"), ("cutscenes_data.c", "\n".join(c) + "\n")):
        path = out / fname
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
    return [n for n, _, _ in files], extra
