"""
Scene types ("game modes") and their engine settings, like GB Studio's
Settings > Engine. The list of settings lives in engine_settings.json
(the editor reads the same file); each becomes one int16 in the engine's
live settings array (engine/include/modes.h, mode_settings.h here).

project.json  "engine": {"pl_jump_vel": 4, "td_grid": 1, ...}   defaults for every scene
scene JSON    "type": "platform", "engine": {"pl_grav": 0.2}     that scene's own overrides

Values are in the editor's units (speeds in px per frame, and so on);
see engine_settings.json's _comment.
"""

import json
import sys
from pathlib import Path


class ModeError(Exception):
    pass


def _settings_path():
    base = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent))
    return base / "engine_settings.json"


TABLE = json.loads(_settings_path().read_text(encoding="utf-8"))
SETTINGS = TABLE["settings"]
SETTING_BY_KEY = {s["key"]: s for s in SETTINGS}
MODES = {m["id"]: m["engine"] for m in TABLE["modes"]}

BUTTON_MASKS = {"a": 0x0001, "b": 0x0002, "select": 0x0004, "start": 0x0008, "right": 0x0010,
                "left": 0x0020, "up": 0x0040, "down": 0x0080, "r": 0x0100, "l": 0x0200}


def scene_mode(scene, where):
    t = scene.get("type") or "topdown"
    t = {"platformer": "platform", "top_down": "topdown"}.get(t, t)
    if t not in MODES:
        raise ModeError(f"{where}: unknown scene \"type\" '{t}'. Use one of: {', '.join(MODES)}.")
    return MODES[t]


def setting_value(key, value, where):
    """One setting in editor units -> the int16 the engine stores."""
    s = SETTING_BY_KEY.get(key)
    if s is None:
        raise ModeError(f"{where}: unknown engine setting '{key}'.")
    unit = s["unit"]
    label = f"{where}: engine setting '{key}' ({s['label']})"
    if unit == "button":
        if isinstance(value, str) and value.lower() in BUTTON_MASKS:
            return BUTTON_MASKS[value.lower()]
        raise ModeError(f"{label} must be a button: {', '.join(BUTTON_MASKS)}.")
    if unit == "bool":
        if isinstance(value, bool) or value in (0, 1):
            return 1 if value else 0
        raise ModeError(f"{label} must be true or false.")
    if unit == "choice":
        options = s["options"]
        if isinstance(value, int) and not isinstance(value, bool) and 0 <= value < len(options):
            return value
        if isinstance(value, str) and value in options:
            return options.index(value)
        raise ModeError(f"{label} must be one of: {', '.join(options)}.")
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        raise ModeError(f"{label} must be a number.")
    lo, hi = s.get("min", -32768), s.get("max", 32767)
    if not lo <= value <= hi:
        raise ModeError(f"{label} must be from {lo} to {hi}.")
    if unit in ("speed", "accel"):
        return int(round(value * 256))
    if value != int(value):
        raise ModeError(f"{label} must be a whole number.")
    return int(value)


def defaults():
    return [setting_value(s["key"], s["default"], "engine_settings.json") for s in SETTINGS]


def resolve(project_engine, scene_engine, where):
    """Project defaults + the scene's overrides -> the full int16 list."""
    values = defaults()
    for source, src_where in ((project_engine, "project.json \"engine\""), (scene_engine, where)):
        if not source:
            continue
        if not isinstance(source, dict):
            raise ModeError(f"{src_where} must be an object of setting: value.")
        for key, value in source.items():
            idx = [s["key"] for s in SETTINGS].index(key) if key in SETTING_BY_KEY else None
            if idx is None:
                raise ModeError(f"{src_where}: unknown engine setting '{key}'.")
            values[idx] = setting_value(key, value, src_where)
    return values


def setting_index(key, where):
    if key not in SETTING_BY_KEY:
        known = ", ".join(s["key"] for s in SETTINGS)
        raise ModeError(f"{where}: unknown engine setting '{key}'. Settings: {known}")
    return [s["key"] for s in SETTINGS].index(key)


def header():
    lines = ["/* Generated by compiler/modes.py from engine_settings.json - do not edit. */",
             "#ifndef MODE_SETTINGS_H", "#define MODE_SETTINGS_H", ""]
    for m in TABLE["modes"]:
        lines.append(f"#define SCENE_MODE_{m['id'].upper():<12} {m['engine']}")
    lines.append("")
    for i, s in enumerate(SETTINGS):
        lines.append(f"#define MS_{s['key'].upper():<22} {i}   /* {s['label']} ({s['unit']}) */")
    lines += ["", f"#define MS_COUNT {len(SETTINGS)}", "", "#endif", ""]
    return "\n".join(lines)
