"""
Sound effects from WAV files -> sounds_data.c/.h (engine/source/wav.c).

    <project>/assets/sounds/<name>.wav

Any PCM WAV (8/16/24/32-bit, mono or stereo, any rate) is mixed to mono,
resampled to the engine's rate and stored as signed 8-bit samples - what
the GBA's two Direct Sound channels play. At 16384 Hz one second is 16 KB
of ROM, so short effects cost little; a whole song as WAV gets big fast
(use .uge music for that).
"""

import array
import sys
import wave
from pathlib import Path

RATE = 16384                 # engine/include/wav.h WAV_RATE
MAX_SECONDS = 60             # a sanity cap on ROM use
PAD = 512                    # silence after the end: DMA reads a bit past it


class WavError(Exception):
    pass


def load_wav(path):
    """A WAV file -> bytes of signed 8-bit mono samples at RATE."""
    try:
        with wave.open(str(path), "rb") as w:
            channels, width, rate, frames = w.getnchannels(), w.getsampwidth(), w.getframerate(), w.getnframes()
            data = w.readframes(frames)
    except (wave.Error, EOFError) as e:
        raise WavError(f"{path.name}: not a WAV file this can read ({e}). Save it as plain PCM "
                       "(8/16-bit) WAV.") from None
    if width not in (1, 2, 3, 4):
        raise WavError(f"{path.name}: {width * 8}-bit samples aren't supported.")
    if channels not in (1, 2):
        raise WavError(f"{path.name}: {channels} channels - use mono or stereo.")
    samples = _to_float_mono(data, width, channels)
    data = _resample_to_s8(samples, rate)
    if len(data) > RATE * MAX_SECONDS:
        raise WavError(f"{path.name}: {len(data) / RATE:.1f}s long; sound effects can be up to "
                       f"{MAX_SECONDS}s (use .uge music for songs).")
    return data


def _to_float_mono(data, width, channels):
    """Raw little-endian PCM -> a list of mono samples in -1..1."""
    if width == 1:
        vals = [(b - 128) / 128.0 for b in data]
    elif width == 2:
        a = array.array("h")
        a.frombytes(data[: len(data) // 2 * 2])
        if sys.byteorder != "little":
            a.byteswap()
        vals = [v / 32768.0 for v in a]
    elif width == 4:
        a = array.array("i")
        a.frombytes(data[: len(data) // 4 * 4])
        if sys.byteorder != "little":
            a.byteswap()
        vals = [v / 2147483648.0 for v in a]
    else:  # 24-bit
        vals = [int.from_bytes(data[i:i + 3], "little", signed=True) / 8388608.0
                for i in range(0, len(data) - 2, 3)]
    if channels == 2:
        vals = [(vals[i] + vals[i + 1]) / 2 for i in range(0, len(vals) - 1, 2)]
    return vals


def _resample_to_s8(vals, rate):
    """Linear resample to RATE, as signed 8-bit bytes."""
    if not vals:
        return b""
    n = max(1, int(len(vals) * RATE / rate))
    step = rate / RATE
    out = bytearray(n)
    last = len(vals) - 1
    wide = step > 1.0     # downsampling: average each step (less aliasing)
    for i in range(n):
        pos = i * step
        j = int(pos)
        if wide:
            k = min(len(vals), max(j + 1, int(pos + step)))
            v = sum(vals[j:k]) / (k - j)
        else:
            f = pos - j
            v = vals[j] if j >= last else vals[j] * (1 - f) + vals[j + 1] * f
        s = int(round(v * 127))
        out[i] = (s if s >= 0 else s + 256) if -128 <= s <= 127 else (127 if s > 0 else 128)
    return bytes(out)


def sound_files(sounds_dir):
    d = Path(sounds_dir)
    return sorted(d.glob("*.wav"), key=lambda p: p.name.lower()) if d.is_dir() else []


def c_ident(name):
    out = "".join(c if c.isalnum() else "_" for c in name)
    return ("s_" + out) if not out[:1].isalpha() else out


def build_sounds(sounds_dir, out_dir, extra=()):
    """Write sounds_data.c/.h; returns the sound names in index order.
    `extra`: [(name, ident, length)] sounds defined elsewhere (a cutscene's
    audio, via .incbin), added after the project's own."""
    files = sound_files(sounds_dir)
    c = ["/* Generated by compiler/wav.py - do not edit. */", "#include <stdint.h>", "",
         '#include "wav.h"', ""]
    names = []
    for p in files:
        data = load_wav(p)
        samples = bytes(data) + bytes(PAD)
        ident = f"wav_{c_ident(p.stem)}"
        rows = [", ".join(str(b - 256 if b > 127 else b) for b in samples[i:i + 32])
                for i in range(0, len(samples), 32)]
        c.append(f"/* {p.name}: {len(data) / RATE:.2f}s */")
        c.append(f"static const int8_t {ident}[{len(samples)}] __attribute__((aligned(4))) = {{\n    "
                 + ",\n    ".join(rows) + "\n};")
        names.append((p.stem, ident, len(data)))
    for name, ident, length in extra:
        c.append(f"extern const int8_t {ident}[];   /* {name} */")
        names.append((name, ident, length))
    if names:
        c.append(f"const WavSound wav_sounds[{len(names)}] = {{")
        for name, ident, length in names:
            c.append(f"    {{ {ident}, {length} }},   /* {name} */")
        c.append("};")
    else:
        c.append("const WavSound wav_sounds[1] = { { 0, 0 } };")
    c.append(f"const uint16_t wav_sound_count = {len(names)};")
    text = "\n".join(c) + "\n"
    path = Path(out_dir) / "sounds_data.c"
    if not path.exists() or path.read_text(encoding="utf-8") != text:
        path.write_text(text, encoding="utf-8")
    return [n for n, _, _ in names]
