#ifndef ADVANCE_HUGE_H
#define ADVANCE_HUGE_H

#include <stdint.h>

/*
 * hUGEDriver, ported from GB Studio's Game Boy assembly
 * (gb-studio-source/src/components/music/helpers/hUGEDriver/
 * hUGEDriver.asm, MIT) to C for the GBA. Plays hUGETracker / GB
 * Studio .uge songs on the GBA's four built-in Game Boy-compatible
 * PSG channels (2x square, wave, noise) - the same hardware the
 * songs were written for, so they sound the same as in GB Studio.
 *
 * Song data is generated by compiler/build_project.py from
 * the .uge files in engine/music/ into engine/data/uge_songs.c. Its byte layout
 * matches hUGEDriver's own (3-byte pattern rows packed by the
 * tracker's "dn" macro, 16-byte waves), so this port can follow the
 * original row-for-row.
 */

/* One instrument. Field meaning depends on the table it's in:
 *   duty:  b0 = NR10 sweep,   b1 = NRx1 length/duty, b2 = NRx2 envelope
 *   wave:  b0 = NR31 length,  b1 = NR32 volume,      b2 = wave index
 *   noise: b0 = NR42 envelope (b1/b2 unused)
 * highmask is the NRx4 "trigger | length enable" bits (noise packs
 * its length and 7-bit-LFSR flag in there too, like hUGEDriver). */
typedef struct {
    uint8_t b0, b1, b2;
    uint8_t highmask;
    const uint8_t *table;   /* subpattern (32 rows x 3 bytes), or NULL */
} HugeInstr;

typedef struct {
    uint8_t ticks_per_row;
    uint8_t order_count;                /* rows in each order list */
    const uint8_t *const *orders[4];    /* per channel: pattern pointers */
    const HugeInstr *duty_instruments;  /* 15 each */
    const HugeInstr *wave_instruments;
    const HugeInstr *noise_instruments;
    const uint8_t *waves;               /* 16 waves x 16 bytes */
} HugeSong;

/* Start a song from the top. Call only between huge_dosound() calls. */
void huge_init(const HugeSong *song);

/* Advance playback by one tick. Call once per frame (GB Studio runs
 * hUGEDriver from the Game Boy's vblank, which is the same ~59.7 Hz
 * as the GBA's). */
void huge_dosound(void);

/* Mute (1) or unmute (0) one channel (0-3). A muted channel is left
 * alone by the driver so sound effects can use it; muting also cuts
 * the note currently playing on it. */
void huge_mute_channel(uint8_t channel, uint8_t mute);

/* 1 once the song has played through its last order and wrapped
 * back to the start (hUGE songs always loop; this lets a caller
 * stop after one pass instead). Reset by huge_init(). */
int huge_song_wrapped(void);

/* Called with the routine id (0-15) whenever a song plays effect
 * 6xx ("call routine"). NULL = ignore 6xx (the default). */
void huge_set_routine_callback(void (*callback)(uint8_t routine));

/* Silence all four PSG channels (used when music stops). */
void huge_silence(void);

#endif
