#ifndef ADVANCE_MODES_H
#define ADVANCE_MODES_H

#include <stdint.h>

#include "entity.h"
#include "scene.h"
#include "script.h"
#include "mode_settings.h"   /* generated by compiler/modes.py */

/*
 * Scene types ("game modes", GB Studio's Top Down / Platformer /
 * Adventure / Shoot Em' Up / Point and Click / Logo): how the player
 * moves and interacts in the current scene. The settings they read
 * (walk speed, gravity, jump...) come from compiler/engine_settings.json
 * via the scene's SceneDef.settings, copied into mode_settings[] on
 * every scene load so "Set Engine Setting" events can change them for
 * the rest of the scene.
 *
 * Speeds are 1/256 px per frame, accelerations 1/256 px per frame^2.
 */
extern int16_t mode_settings[MS_COUNT];
#define MSET(key) (mode_settings[MS_##key])

/* Animation states a sprite may have, found by name (compiler: "jump",
 * "fall", ...) - SpriteDef.mode_states. */
enum
{
    MODE_ANIM_JUMP, MODE_ANIM_FALL, MODE_ANIM_CLIMB, MODE_ANIM_RUN, MODE_ANIM_DASH,
    MODE_ANIM_WALL, MODE_ANIM_FLOAT, MODE_ANIM_KNOCKBACK, MODE_ANIM_CROUCH,
    MODE_ANIM_HOVER, MODE_ANIM_PUSH,
    MODE_ANIM_COUNT
};

void modes_scene_enter(const SceneDef *scene, Entity *player);
int modes_current(void);

/* One frame of normal play (no script or dialogue running): player
 * movement and input. Returns a script to start as the main script
 * (talking to an actor, clicking a trigger...), or 0. */
const ScriptEvent *modes_update(Entity *player);

/* Where the camera should centre this frame, if the mode decides (1);
 * 0 = the usual: follow the player. */
int modes_camera(Entity *player, int *center_x, int *center_y);

/* Should the usual "step into a trigger" check run? (Point and Click
 * clicks them; Shoot Em' Up can fire them as they scroll on screen.) */
int modes_uses_step_triggers(void);

/* The player was hit by something at (from_x, from_y): knockback. */
void modes_player_hit(Entity *player, int from_x, int from_y);

/* Show or hide the player (Logo scenes hide it). */
int modes_player_visible(void);

/* SCRIPT_SET_ENGINE_SETTING. */
void modes_set_setting(int index, int value);

#endif
