#include <maxmod.h>

#include "music.h"          /* also pulls in soundbank.h (MOD_* ids) */
#include "soundbank_bin.h"  /* generated by the Makefile's bin2o rule -
                              declares the soundbank_bin[] data array
                              mmInitDefault needs */

#define MUSIC_CHANNELS 8   /* simultaneous samples Maxmod can mix */

void music_init(void)
{
    mmInitDefault((mm_addr)soundbank_bin, MUSIC_CHANNELS);
}

void music_update(void)
{
    /* Standard GBA Maxmod API: the tracker's timing is driven by
     * this once-per-vblank call, not a separate frame-poll function. */
    mmVBlank();
}

void music_play(int track_id, int loop)
{
    mmStart(track_id, loop ? MM_PLAY_LOOP : MM_PLAY_ONCE);
}

void music_stop(void)
{
    mmStop();
}
