/**
 * Runs the two-step Shimmer Engine build (compiler/build_project.py, then
 * `make -C engine`) as a child process, mirroring the toolchain root's
 * reference build.sh (see this feature's task description - it's not
 * assumed to exist or be unmodified, so the same logic is reimplemented
 * here directly rather than shelling out to that file).
 *
 * Isolated from electron/main.ts's IPC wiring for the same reason
 * projectIO.ts is: so the command-construction and path-translation logic
 * (the only parts of this that can actually be verified without a real
 * Windows+WSL+devkitARM machine - see the module's test notes) can be
 * exercised on its own.
 */

import { spawn } from "node:child_process";
import type { ChildProcessByStdio } from "node:child_process";
import { existsSync, statSync } from "node:fs";
import { writeFile, unlink, readFile } from "node:fs/promises";
import path from "node:path";
import type { Readable } from "node:stream";

import type { BuildLogEvent, BuildRomResult } from "../shared/ipc.js";

/** How many trailing lines of combined stdout/stderr to include in a
 * failure message - enough to see a compiler BuildError or a devkitARM
 * error, without dumping an entire noisy `make` log into a one-line error
 * string. The full output is already visible to the user via the
 * streamed BuildLogEvents regardless. */
const ERROR_TAIL_LINES = 60;

/**
 * Translates a Windows drive path to its WSL mount equivalent:
 * `C:\Users\User\Desktop\gba studio` -> `/mnt/c/Users/User/Desktop/gba studio`.
 * Lowercases the drive letter, swaps backslashes for forward slashes, and
 * prefixes `/mnt/<letter>/` - the standard WSL2 mount scheme. Throws
 * rather than guessing when the input doesn't look like a drive path
 * (e.g. it's already a UNC or POSIX path), since a silently-wrong
 * translation would fail confusingly deep inside `wsl.exe` instead of
 * here where it's obvious what went wrong.
 */
export function windowsPathToWsl(winPath: string): string {
  const m = /^([A-Za-z]):[\\/]?(.*)$/.exec(winPath);
  if (!m) {
    throw new Error(
      `"${winPath}" doesn't look like a Windows drive path (expected something like "C:\\Users\\...").`,
    );
  }
  const drive = m[1].toLowerCase();
  const rest = m[2].replace(/\\/g, "/");
  return `/mnt/${drive}/${rest}`;
}

/** Wraps a string in single quotes for safe interpolation into a
 * `bash -lc "..."` command line, escaping any single quotes it contains.
 * The toolchain root and project paths this feature deals with routinely
 * have spaces in them (see the user's actual path,
 * `C:\Users\User\Desktop\gba studio\...`), so naive unquoted
 * interpolation would silently split the command wrong. */
export function shQuote(s: string): string {
  return `'${s.split("'").join(`'\\''`)}'`;
}

/**
 * The bash script a dev build runs (inside WSL on Windows): the toolchain's
 * compiler/build_rom.py, which runs the project compiler, compiles the
 * engine with devkitARM and writes the ROM - no make involved, so paths
 * with spaces are fine. The interpreter is picked inside the shell that
 * runs the build (a local .venv, else python3, else python), since on
 * Windows that's inside WSL, which this process can't inspect.
 *
 * It's written to a file and run as `bash <file>` rather than passed as one
 * long `-c` argument: wsl.exe has been seen to mangle long single-argument
 * commands during a cold start.
 */
export function buildScriptContent(toolchainRootPosix: string, projectPosix: string, romPosix: string): string {
  return [
    `#!/usr/bin/env bash`,
    `# Auto-generated by Shimmer Engine's "Build ROM" - safe to delete.`,
    `set -e`,
    `cd ${shQuote(toolchainRootPosix)}`,
    `if [ -x .venv/bin/python ]; then`,
    `  PY=.venv/bin/python`,
    `elif command -v python3 >/dev/null 2>&1; then`,
    `  PY=python3`,
    `else`,
    `  PY=python`,
    `fi`,
    `echo "[shimmer-engine] using interpreter: $PY"`,
    `"$PY" compiler/build_rom.py ${shQuote(projectPosix)} --out ${shQuote(romPosix)}`,
    ``,
  ].join("\n");
}

/** Kept only so anything that still imports the old name (e.g. a stale
 * build of this file elsewhere) fails loudly instead of silently linking
 * against removed behavior. Not used by buildRom() anymore. */
export const buildShellCommand = buildScriptContent;

/** File name (not path) of the generated build script - written to, and
 * cleaned up from, the toolchain root itself, since that's a location
 * that's the same path on the Windows side and (via windowsPathToWsl) on
 * the WSL side. Excluded from the rsync mirror step above so it isn't
 * pointlessly duplicated into the mirror on every build. */
const BUILD_SCRIPT_NAME = ".shimmer-engine-build.sh";

/** Picks the exported ROM's file name: the project's own `name` field
 * from project.json (sanitized the same way createProject() derives a
 * folder name from it), falling back to the project folder's own name if
 * project.json is missing/unreadable/unnamed. Always ends in ".gba". */
async function romFileName(rootPath: string): Promise<string> {
  let base = path.basename(rootPath);
  try {
    const raw = await readFile(path.join(rootPath, "project.json"), "utf-8");
    const parsed = JSON.parse(raw) as { name?: unknown };
    if (typeof parsed.name === "string" && parsed.name.trim()) {
      base = parsed.name.trim();
    }
  } catch {
    // project.json missing or unreadable - fall back to the folder name.
  }
  const safe = base
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return `${safe || "rom"}.gba`;
}

interface RunningBuild {
  child: ChildProcessByStdio<null, Readable, Readable>;
  cancelled: boolean;
}

let current: RunningBuild | null = null;

export function isBuildRunning(): boolean {
  return current !== null;
}

/** Kills the in-progress build, if any. Returns false if nothing was
 * running. Note: on Windows the child process is `wsl.exe` itself, not
 * the build inside the WSL VM directly - killing it terminates that WSL
 * invocation, which is the most this process can do from here without
 * reaching into the WSL VM's own process table. */
export function cancelBuild(): boolean {
  if (!current) return false;
  current.cancelled = true;
  try {
    current.child.kill();
  } catch {
    // Best effort - if the process already exited, there's nothing to do.
  }
  return true;
}

function tail(lines: string[], n: number): string {
  return lines.slice(-n).join("\n");
}

function startFailureMessage(toolchainRoot: string, isWindows: boolean, err: unknown): string {
  const base = err instanceof Error ? err.message : String(err);
  if (isWindows) {
    const scriptName = ["install-devkitpro-pacman", "install-devkitpro-pacman.sh"].find((name) =>
      existsSync(path.join(toolchainRoot, name)),
    );
    const hint = scriptName
      ? ` This toolchain has a "${scriptName}" script at its root - if WSL and devkitARM aren't set up yet, that's likely the one to run (from inside WSL). If WSL itself isn't installed, run "wsl --install" from an admin PowerShell first.`
      : ` Make sure WSL2 is installed ("wsl --install" from an admin PowerShell) and devkitARM is set up inside it.`;
    return `Couldn't start WSL to run the build (${base}).${hint}`;
  }
  return `Couldn't start the build (${base}). Make sure "bash" and "make" are on your PATH and devkitARM is installed.`;
}

/**
 * Runs the build for the project at `rootPath`, inside the toolchain at
 * `toolchainRoot` (the folder containing engine/Makefile - see
 * projectIO.findEngineRoot). `sendLog` is called with each streamed line
 * as it arrives, plus a few status lines of this function's own. Only
 * one build may run at a time process-wide; call isBuildRunning() first
 * if you need to guard against a concurrent call (electron/main.ts does).
 */
export async function buildRom(
  rootPath: string,
  toolchainRoot: string,
  sendLog: (event: BuildLogEvent) => void,
): Promise<BuildRomResult> {
  if (current) {
    return { ok: false, error: "A build is already running." };
  }

  const isWindows = process.platform === "win32";
  const romFile = await romFileName(rootPath);
  const romPath = path.join(rootPath, "ROM", romFile);
  const bundledBuilder = path.join(toolchainRoot, isWindows ? "shimmer-build.exe" : "shimmer-build");
  const bundled = existsSync(bundledBuilder);

  let commandProgram: string;
  let commandArgs: string[];
  let scriptNativePath: string | null = null;

  if (bundled) {
    // The installed app: its own build tool, engine and devkitARM.
    commandProgram = bundledBuilder;
    commandArgs = [
      rootPath,
      "--engine",
      path.join(toolchainRoot, "engine"),
      "--devkitpro",
      path.join(toolchainRoot, "devkitpro"),
      "--out",
      romPath,
    ];
  } else {
    // A checkout: build_rom.py through bash (WSL on Windows), with
    // devkitARM from the user's own setup.
    let toPosix = (p: string) => p;
    if (isWindows) toPosix = windowsPathToWsl;
    let script: string;
    try {
      script = buildScriptContent(toPosix(toolchainRoot), toPosix(rootPath), toPosix(romPath));
    } catch (err) {
      return { ok: false, error: `Couldn't translate a path for WSL: ${err instanceof Error ? err.message : String(err)}` };
    }
    scriptNativePath = path.join(toolchainRoot, BUILD_SCRIPT_NAME);
    try {
      await writeFile(scriptNativePath, script, "utf-8");
    } catch (err) {
      return {
        ok: false,
        error: `Couldn't write the build script to ${scriptNativePath}: ${err instanceof Error ? err.message : String(err)}`,
      };
    }
    const scriptPosix = toPosix(scriptNativePath);
    commandProgram = isWindows ? "wsl.exe" : "bash";
    commandArgs = isWindows ? ["bash", "-l", scriptPosix] : ["-l", scriptPosix];
  }

  sendLog({ stream: "status", line: bundled ? "Building…" : `Running: ${commandProgram} ${commandArgs.join(" ")}` });

  // Snapshot the ROM's current mtime (if it exists) so a build that
  // reports success can be checked against actually having rewritten it -
  // see the comment at the success check below for why this matters.
  let preBuildMtimeMs: number | null = null;
  try {
    preBuildMtimeMs = statSync(romPath).mtimeMs;
  } catch {
    preBuildMtimeMs = null; // no ROM yet - any successful build is "fresh"
  }

  const cleanupScript = () => {
    if (!scriptNativePath) return;
    unlink(scriptNativePath).catch(() => {
      // Best effort - leaving the script behind doesn't break the next
      // build (it's overwritten each time) and can help debugging.
    });
  };

  return new Promise((resolve) => {
    let child: ChildProcessByStdio<null, Readable, Readable>;
    try {
      child = spawn(commandProgram, commandArgs, { stdio: ["ignore", "pipe", "pipe"] });
    } catch (err) {
      cleanupScript();
      resolve({ ok: false, error: startFailureMessage(toolchainRoot, isWindows, err) });
      return;
    }

    const handle: RunningBuild = { child, cancelled: false };
    current = handle;

    const outLines: string[] = [];
    const allLines: string[] = [];
    let settled = false;

    const makePump = (stream: "stdout" | "stderr") => {
      let buf = "";
      return (chunk: Buffer) => {
        buf += chunk.toString("utf-8");
        const parts = buf.split(/\r?\n/);
        buf = parts.pop() ?? "";
        for (const line of parts) {
          if (stream === "stdout") outLines.push(line);
          allLines.push(line);
          sendLog({ stream, line });
        }
      };
    };
    child.stdout.on("data", makePump("stdout"));
    child.stderr.on("data", makePump("stderr"));

    // Fires when the process itself couldn't be started (e.g. wsl.exe or
    // bash isn't on PATH at all) - distinct from a build that started and
    // then failed, which is handled in the "close" listener below via a
    // non-zero exit code.
    child.on("error", (err) => {
      if (settled) return;
      settled = true;
      current = null;
      cleanupScript();
      resolve({ ok: false, error: startFailureMessage(toolchainRoot, isWindows, err) });
    });

    child.on("close", (code) => {
      if (settled) return;
      settled = true;
      current = null;
      cleanupScript();

      if (handle.cancelled) {
        sendLog({ stream: "status", line: "Build cancelled." });
        resolve({ ok: false, error: "Build cancelled." });
        return;
      }

      const romExists = existsSync(romPath);
      // A process exit code of 0 isn't proof anything actually happened -
      // this exact bug shipped once already (see buildScriptContent's doc
      // comment): the interpreter-detection step silently produced an
      // empty command, the rest of the script never ran, but the shell's
      // own exit code was still 0 and an *old* engine.gba from a previous
      // build was still sitting there, so a naive "exit 0 and the file
      // exists" check reported success on a completely stale ROM. Requiring
      // the file's mtime to have actually moved forward catches that class
      // of silent no-op regardless of its cause.
      let romIsFresh = false;
      if (romExists) {
        try {
          const postBuildMtimeMs = statSync(romPath).mtimeMs;
          romIsFresh = preBuildMtimeMs === null || postBuildMtimeMs > preBuildMtimeMs;
        } catch {
          romIsFresh = false;
        }
      }

      if (code === 0 && romExists && romIsFresh) {
        sendLog({ stream: "status", line: `Build succeeded: ${romPath}` });
        resolve({ ok: true, romPath });
        return;
      }

      const combinedTail = tail(allLines, ERROR_TAIL_LINES) || "(no output captured)";
      let error: string;
      if (code === 0 && !romExists) {
        error = `The build reported success but no ROM was found at ${romPath}. Last output:\n${combinedTail}`;
      } else if (code === 0 && romExists && !romIsFresh) {
        error =
          `The build reported success but ${romPath} was never rewritten (still the same file from before ` +
          `this build ran). Something in the build script silently did nothing - check the log above for the ` +
          `last real output before it stopped. Last output:\n${combinedTail}`;
      } else {
        error = `Build failed (exit code ${code ?? "unknown"}). Last output:\n${combinedTail}`;
      }
      sendLog({ stream: "status", line: error });
      resolve({ ok: false, error });
    });
  });
}
