#include <gba.h>
#include <stdint.h>

#include "input.h"
#include "sprite.h"
#include "background.h"
#include "camera.h"
#include "collision.h"
#include "entity.h"
#include "scene.h"
#include "transition.h"
#include "dialogue.h"
#include "menu.h"
#include "audio.h"
#include "music.h"
#include "save.h"
#include "debug.h"
#include "script.h"
#include "state.h"
#include "actor.h"
#include "rng.h"
#include "timer.h"
#include "game.h"

#include "scenes_data.h"      /* generated by compiler/build_project.py */

#define PLAYER_SPEED      1   /* pixels per frame */
#define PLAYER_PALETTE    0   /* OBJ palette bank */

#define NPC_MAX           16  /* max NPCs alive at once */

/* How far in front of the player (from its center) an A-press reaches. */
#define INTERACT_REACH    12

/*
 * Scene-transition state machine.
 * PLAY      = normal gameplay (includes dialogue/scripts - see
 *             dialogue_active()/script_active())
 * MENU      = pause menu open (START)
 * FADE_OUT  = a script hit SCRIPT_SWITCH_SCENE, darkening screen
 * LOADING   = screen is black, load the target scene
 * FADE_IN   = brightening into new scene
 */
typedef enum
{
    STATE_PLAY,
    STATE_MENU,
    STATE_FADE_OUT,
    STATE_LOADING,
    STATE_FADE_IN
} GameState;

static GameState game_state = STATE_PLAY;

/* Where SCRIPT_SWITCH_SCENE is headed - filled by
 * script_wants_scene_switch(), consumed by STATE_LOADING. */
static int pending_switch_scene = 0;
static int pending_switch_x = 0;
static int pending_switch_y = 0;
static int pending_switch_dir = -1;

/* The trigger zone ("door") the player is currently standing inside, or
 * 0 if none - lets the STATE_PLAY door check below edge-trigger
 * on_enter (fire only the frame the player steps into the zone) instead
 * of level-triggering it (refiring every frame they keep standing in
 * it once a non-scene-switching on_enter script finishes - the door
 * check is only reached again once script_active()/dialogue_active()
 * both go false, and without this the player is still standing in the
 * same zone at that point). Reset to 0 on every scene load, since a
 * stale pointer into the previous scene's doors[] array must never be
 * compared against the new one's. */
static const DoorDef *door_last_entered = 0;

/*
 * A scene's music_track of -1 means "no opinion, leave whatever's
 * playing" (e.g. most scenes, until you're giving them their own
 * track) - see "music" in scene JSON / scene.h. Compares against
 * music_current_track() (music.h), not a local static, so this
 * correctly skips restarting a track a SCRIPT_PLAY_MUSIC already
 * started (e.g. from an On Init before a door walk), and vice versa.
 */
static void play_scene_music(const SceneDef *scene)
{
    if (scene->music_track < 0 || scene->music_track == music_current_track())
        return;

    music_play(scene->music_track, 1);
}

/* Active NPC entities for the current scene, and the ROM defs they
 * came from (same order, same index) so interaction can look up
 * each NPC's on_interact script. */
static Entity      *npc_entities[NPC_MAX];
static const NpcDef *npc_defs[NPC_MAX];
static int           npc_count_active = 0;

/* The player Entity, set once right after it's created at boot (see
 * main()) and never reassigned after - lets actor_*() below (and
 * sync_camera()) target the player the same way they target an NPC,
 * for "actor" script fields set to "player" (see actor.h's
 * PLAYER_ACTOR_INDEX). */
static Entity      *g_player = 0;

/* OAM/VRAM watermark taken right after the player's sprite is created
 * (see sprite_alloc_mark() in sprite.h): every scene change rewinds the
 * sprite allocator to it, releasing the previous scene's NPC sprites
 * instead of leaking them. 0 until the player exists. */
static uint32_t      scene_sprite_mark = 0;
static int           scene_sprite_marked = 0;

/*
 * Per-slot wander state for NPCs with movement == 1 (see scene.h).
 * Tile-collision aware only (via entity_can_move, same as the
 * player) - doesn't check against the player or other NPCs, so brief
 * cosmetic overlap is possible. Re-rolled by update_wandering_npc()
 * whenever npc_wander_timer[i] counts down to 0.
 */
static uint16_t npc_wander_timer[NPC_MAX];
static uint8_t  npc_wander_dir[NPC_MAX];     /* Direction */
static uint8_t  npc_wander_moving[NPC_MAX];  /* 0 = idling, 1 = walking */

/*
 * Camera lock state (see camera.h's camera_lock_to_actor()/
 * camera_lock_to_point()/camera_step_to()/camera_release(), and
 * SCRIPT_CAMERA_* in script.h). camera_locked == 0 is the default:
 * ordinary gameplay calls camera_follow(player) every frame, same as
 * always. While locked, that stops (see sync_camera() below) - either
 * a specific actor is tracked every frame (camera_lock_actor_index
 * >= 0), or the camera just stays wherever camera_lock_to_point()/
 * camera_step_to() last put it (camera_lock_actor_index == -1).
 */
static int camera_locked = 0;
static int camera_lock_actor_index = -1;

/*
 * Background timers (see timer.h, SCRIPT_START_TIMER in script.h).
 * Index matches the current scene's TimerDef array (scene.h) - reset
 * whenever a new scene loads, since a scene's timer indices mean
 * nothing once its TimerDef array is gone.
 */
#define MAX_TIMERS 8   /* keep in sync with compiler/build_project.py's
                         * own MAX_TIMERS */
static int timer_frames_left[MAX_TIMERS];
static int timer_running[MAX_TIMERS];   /* 0 = not armed */

static void setup_player_palette(void)
{
    sprite_load_palette(PLAYER_PALETTE, sprite_defs[player_sprite_index].palette);
}

/*
 * Destroy all current NPC entities, then spawn the ones defined
 * by the scene. Loads each sprite's OBJ palette as needed.
 */
static void scene_entities_load(const SceneDef *scene)
{
    /* Tear down the previous scene's NPCs. */
    for (int i = 0; i < npc_count_active; i++)
    {
        if (npc_entities[i])
        {
            entity_destroy(npc_entities[i]);
            npc_entities[i] = 0;
        }
        npc_defs[i] = 0;
    }
    npc_count_active = 0;

    /* Give the torn-down NPCs' OAM entries/VRAM tiles back. */
    if (scene_sprite_marked)
        sprite_alloc_reset(scene_sprite_mark);

    if (!scene->npcs || scene->npc_count == 0)
        return;

    int n = scene->npc_count;
    if (n > NPC_MAX)
        n = NPC_MAX;

    for (int i = 0; i < n; i++)
    {
        const NpcDef    *def = &scene->npcs[i];
        const SpriteDef *spr = &sprite_defs[def->sprite_index];

        /* This sprite's palette, in the bank the compiler gave it for
         * this scene (sprites with identical colors share one). */
        sprite_load_palette(def->palette_bank, spr->palette);

        Entity *e = entity_create(ENTITY_NPC, def->x, def->y, 16, 16);
        if (!e)
            break;

        e->solid = 1;
        e->direction = def->direction;
        entity_set_sprite(e, spr, def->palette_bank);

        npc_entities[npc_count_active] = e;
        npc_defs[npc_count_active] = def;
        npc_wander_timer[npc_count_active] = 0;
        npc_wander_moving[npc_count_active] = 0;
        npc_count_active++;
    }
}

/* Direction -> per-frame step, indexed DOWN,UP,RIGHT,LEFT (see entity.h). */
static const int WANDER_DX[4] = { 0, 0, 1, -1 };
static const int WANDER_DY[4] = { 1, -1, 0, 0 };

static void update_wandering_npc(int i)
{
    Entity *npc = npc_entities[i];

    if (npc_wander_timer[i] > 0)
    {
        npc_wander_timer[i]--;
    }
    else
    {
        uint32_t r = rng_next();

        npc_wander_moving[i] = (uint8_t)(r & 1u);
        npc_wander_dir[i]    = (uint8_t)((r >> 1) & 3u);
        npc_wander_timer[i]  = (uint16_t)(30 + (r % 60));

        if (!npc_wander_moving[i])
            entity_animate(npc, (Direction)npc_wander_dir[i], 0);
    }

    if (!npc_wander_moving[i])
        return;

    int nx = npc->x + WANDER_DX[npc_wander_dir[i]];
    int ny = npc->y + WANDER_DY[npc_wander_dir[i]];
    int moved = 0;

    if (entity_can_move(npc, nx, ny))
    {
        npc->x = nx;
        npc->y = ny;
        moved = 1;
    }
    else
    {
        /* Something's in the way - stop this window instead of
         * pushing against it every frame until it re-rolls anyway. */
        npc_wander_timer[i] = 0;
    }

    entity_animate(npc, (Direction)npc_wander_dir[i], moved);
}

/*
 * Combined movement check: tile collision + NPC blocking.
 */
static int player_can_move(Entity *player, int x, int y)
{
    if (!entity_can_move(player, x, y))
        return 0;

    /* Both boxes' authored offset/size (defaults to the full sprite
     * rect - see Entity's col_ox/col_oy/col_w/col_h in entity.h) at the
     * player's PROPOSED position (x, y), not its current one. */
    int px = x + player->col_ox;
    int py = y + player->col_oy;
    int pw = player->col_w;
    int ph = player->col_h;

    for (int i = 0; i < npc_count_active; i++)
    {
        Entity *npc = npc_entities[i];
        if (!npc || !npc->solid)
            continue;

        int nx = npc->x + npc->col_ox;
        int ny = npc->y + npc->col_oy;

        if (px < nx + npc->col_w &&
            px + pw > nx &&
            py < ny + npc->col_h &&
            py + ph > ny)
        {
            return 0;
        }
    }

    return 1;
}

/*
 * Look for an NPC in front of the player (facing direction, a short
 * reach out from the player's center). Returns its on_interact
 * script, or 0 if nothing interactable is there.
 */
static const ScriptEvent *check_npc_interact(Entity *player)
{
    int cx = player->x + player->width / 2;
    int cy = player->y + player->height / 2;

    switch ((Direction)player->direction)
    {
    case DIR_DOWN:  cy += INTERACT_REACH; break;
    case DIR_UP:    cy -= INTERACT_REACH; break;
    case DIR_RIGHT: cx += INTERACT_REACH; break;
    case DIR_LEFT:  cx -= INTERACT_REACH; break;
    }

    for (int i = 0; i < npc_count_active; i++)
    {
        Entity *npc = npc_entities[i];
        /* Hidden (actor_set_visible(i, 0)) NPCs are fully "not
         * there" - not just invisible, not talkable either. */
        if (!npc || !npc->solid)
            continue;

        if (cx >= npc->x && cx < npc->x + npc->width &&
            cy >= npc->y && cy < npc->y + npc->height)
        {
            return npc_defs[i]->on_interact;
        }
    }

    return 0;
}

/*
 * Runtime actor control from event scripts - see actor.h/script.h.
 * `index` is either the NPC's position in the CURRENT scene's npcs[]
 * list (same order as npc_entities[]/npc_defs[]), or
 * PLAYER_ACTOR_INDEX for the player - see entity_for_actor() below.
 */

/* Resolves a SCRIPT_ACTOR_* `index` operand to the Entity it targets:
 * the player (PLAYER_ACTOR_INDEX - see actor.h), or an NPC in the
 * current scene. 0 for anything else (an out-of-range NPC index, or
 * before the player exists yet). */
static Entity *entity_for_actor(int index)
{
    if (index == PLAYER_ACTOR_INDEX)
        return g_player;

    if (index < 0 || index >= npc_count_active || !npc_entities[index])
        return 0;

    return npc_entities[index];
}

void actor_set_visible(int index, int visible)
{
    Entity *e = entity_for_actor(index);
    if (!e)
        return;

    if (visible)
    {
        sprite_show(&e->sprite);
        e->solid = 1;
    }
    else
    {
        sprite_hide(&e->sprite);
        e->solid = 0;
    }
}

void actor_set_position(int index, int x, int y)
{
    Entity *e = entity_for_actor(index);
    if (!e)
        return;

    e->x = x;
    e->y = y;
}

void actor_set_direction(int index, int direction)
{
    Entity *e = entity_for_actor(index);
    if (!e)
        return;

    entity_animate(e, (Direction)direction, 0);
}

void actor_set_state(int index, int state_index)
{
    Entity *e = entity_for_actor(index);
    if (!e)
        return;

    entity_set_anim_state(e, state_index);
}

void actor_set_animate(int index, int enabled)
{
    Entity *e = entity_for_actor(index);
    if (!e)
        return;

    entity_set_animate(e, enabled);
}

void actor_set_frame(int index, int frame)
{
    Entity *e = entity_for_actor(index);
    if (!e)
        return;

    entity_set_frame(e, frame);
}

void actor_set_collision_box(int index, int ox, int oy, int w, int h)
{
    Entity *e = entity_for_actor(index);
    if (!e)
        return;

    entity_set_collision_box(e, ox, oy, w, h);
}

int actor_get_x(int index)
{
    Entity *e = entity_for_actor(index);
    return e ? e->x : 0;
}

int actor_get_y(int index)
{
    Entity *e = entity_for_actor(index);
    return e ? e->y : 0;
}

int actor_get_direction(int index)
{
    Entity *e = entity_for_actor(index);
    return e ? e->direction : 0;
}

/* Move one coordinate at most `speed` px closer to `target`, clamped
 * so it never overshoots. Shared by actor_step_toward() below. */
static int step_toward(int current, int target, int speed)
{
    if (current < target)
    {
        current += speed;
        if (current > target)
            current = target;
    }
    else if (current > target)
    {
        current -= speed;
        if (current < target)
            current = target;
    }

    return current;
}

int actor_step_toward(int index, int target_x, int target_y)
{
    Entity *npc = entity_for_actor(index);
    if (!npc)
        return 0;

    /* X fully, then Y - same one-axis-at-a-time shape as the wander
     * movement above, since the sprite can only face one axis. */
    if (npc->x != target_x)
    {
        Direction dir = (target_x > npc->x) ? DIR_RIGHT : DIR_LEFT;
        npc->x = step_toward(npc->x, target_x, npc->move_speed ? npc->move_speed : 1);
        entity_animate(npc, dir, 1);
        return 1;
    }

    if (npc->y != target_y)
    {
        Direction dir = (target_y > npc->y) ? DIR_DOWN : DIR_UP;
        npc->y = step_toward(npc->y, target_y, npc->move_speed ? npc->move_speed : 1);
        entity_animate(npc, dir, 1);
        return 1;
    }

    entity_animate(npc, (Direction)npc->direction, 0);   /* arrived - stop */
    return 0;
}

void actor_set_move_speed(int index, int speed)
{
    Entity *e = entity_for_actor(index);
    if (!e)
        return;
    if (speed < 1) speed = 1;
    if (speed > 8) speed = 8;
    e->move_speed = (uint8_t)speed;
}

void actor_set_anim_speed(int index, int speed)
{
    Entity *e = entity_for_actor(index);
    if (e)
        e->anim_speed = (uint8_t)(speed < 0 ? 0 : speed > 255 ? 255 : speed);
}

void actor_set_collisions(int index, int enabled)
{
    Entity *e = entity_for_actor(index);
    if (e)
        e->collide = enabled ? 1 : 0;
}

int actor_push_target(int index, int slide, int *x, int *y)
{
    Entity *e = entity_for_actor(index);
    if (!e || !g_player)
        return 0;

    static const int DX[4] = { 0, 0, 1, -1 };
    static const int DY[4] = { 1, -1, 0, 0 };
    int d = g_player->direction & 3;
    int tx = e->x;
    int ty = e->y;

    /* 16px per step, checked every 8px so a wall between isn't skipped. */
    for (int step = 0; step < (slide ? 32 : 1); step++)
    {
        int nx = tx + DX[d] * 16;
        int ny = ty + DY[d] * 16;
        if (!entity_can_move(e, tx + DX[d] * 8, ty + DY[d] * 8) ||
            !entity_can_move(e, nx, ny))
            break;
        tx = nx;
        ty = ny;
    }

    if (tx == e->x && ty == e->y)
        return 0;
    *x = tx;
    *y = ty;
    return 1;
}

/* Forward declaration - defined further down. */
static int scene_to_index(const SceneDef *target);

int game_scene_index(void)
{
    return scene_to_index(scene_current());
}

static void fill_save(SaveData *save_data)
{
    save_data->flags = state_flags();
    save_data->inventory = state_inventory();
    save_data->scene_index = (uint8_t)scene_to_index(scene_current());
    save_data->player_x = (int16_t)(g_player ? g_player->x : 0);
    save_data->player_y = (int16_t)(g_player ? g_player->y : 0);
    save_data->player_direction = g_player ? g_player->direction : 0;

    const int16_t *vars = state_variables();
    for (int i = 0; i < MAX_VARIABLES; i++)
        save_data->variables[i] = vars[i];
}

void game_save_slot(int slot)
{
    SaveData save_data;
    fill_save(&save_data);
    save_write_slot(slot, &save_data);
}

int game_load_slot(int slot)
{
    SaveData save_data;
    if (!save_read_slot(slot, &save_data))
        return 0;
    if (save_data.scene_index >= SCENE_COUNT)
        return 0;

    state_init(save_data.flags, save_data.inventory, save_data.variables);
    script_request_scene_switch(save_data.scene_index, save_data.player_x,
                                save_data.player_y, save_data.player_direction);
    return 1;
}

#define SCENE_STACK_MAX 8
static struct { uint8_t scene; int16_t x, y; uint8_t dir; } scene_stack[SCENE_STACK_MAX];
static int scene_stack_count = 0;

void game_scene_push(void)
{
    if (scene_stack_count >= SCENE_STACK_MAX || !g_player)
        return;
    scene_stack[scene_stack_count].scene = (uint8_t)game_scene_index();
    scene_stack[scene_stack_count].x = (int16_t)g_player->x;
    scene_stack[scene_stack_count].y = (int16_t)g_player->y;
    scene_stack[scene_stack_count].dir = g_player->direction;
    scene_stack_count++;
}

int game_scene_pop(int all)
{
    if (scene_stack_count == 0)
        return 0;
    int i = all ? 0 : scene_stack_count - 1;
    scene_stack_count = i;
    script_request_scene_switch(scene_stack[i].scene, scene_stack[i].x,
                                scene_stack[i].y, scene_stack[i].dir);
    return 1;
}

void game_scene_reset(void)
{
    scene_stack_count = 0;
}

/*
 * Script-driven camera control (declared in camera.h; see the doc
 * comment there for why these live here instead of in camera.c).
 */
void camera_lock_to_actor(int index)
{
    camera_locked = 1;
    camera_lock_actor_index = index;
}

void camera_lock_to_point(int x, int y)
{
    camera_locked = 1;
    camera_lock_actor_index = -1;
    camera_follow(x, y);
}

int camera_step_to(int target_x, int target_y, int speed)
{
    camera_locked = 1;
    camera_lock_actor_index = -1;

    int cx = camera_get_x() + SCREEN_WIDTH / 2;
    int cy = camera_get_y() + SCREEN_HEIGHT / 2;

    if (cx == target_x && cy == target_y)
        return 0;

    if (speed < 1)
        speed = 1;
    cx = step_toward(cx, target_x, speed);
    cy = step_toward(cy, target_y, speed);

    camera_follow(cx, cy);
    return 1;
}

void camera_release(void)
{
    camera_locked = 0;
    camera_lock_actor_index = -1;
}

/*
 * Camera-follow resolution + repositioning everyone on screen relative
 * to it - called every STATE_PLAY frame (dialogue-active, script-
 * active, and normal movement alike), so a script that locks the
 * camera to a moving actor, or pans it itself, stays visually in sync
 * no matter which of those three sub-branches is running that frame.
 * See camera_locked/camera_lock_actor_index above.
 */
static void sync_camera(Entity *player)
{
    if (camera_locked && camera_lock_actor_index == PLAYER_ACTOR_INDEX)
    {
        /* Locked to "the player" specifically - same math as the
         * unlocked (default) case below, just reachable explicitly
         * via a Camera Follow Actor event targeting "player" (e.g.
         * to return to following the player after having locked onto
         * an NPC, without a plain Camera Release). */
        camera_follow(
            player->x + player->width / 2,
            player->y + player->height / 2
        );
    }
    else if (camera_locked && camera_lock_actor_index >= 0 &&
        camera_lock_actor_index < npc_count_active &&
        npc_entities[camera_lock_actor_index])
    {
        Entity *cam_npc = npc_entities[camera_lock_actor_index];
        camera_follow(
            cam_npc->x + cam_npc->width / 2,
            cam_npc->y + cam_npc->height / 2
        );
    }
    else if (!camera_locked)
    {
        camera_follow(
            player->x + player->width / 2,
            player->y + player->height / 2
        );
    }
    /* else: locked to a fixed point - camera_lock_to_point()/
     * camera_step_to() already positioned it directly above. */

    /* Display (possibly shake-jittered) position, not the clean
     * camera_get_x()/camera_get_y() - so a screen shake moves every
     * sprite in step with the background it's drawn over instead of
     * the background jittering under otherwise-static characters. See
     * camera_get_display_x()'s doc comment in camera.h for why this
     * has to be a separate pair of getters from the clean ones. */
    int draw_x = camera_get_display_x();
    int draw_y = camera_get_display_y();

    entity_update_camera(player, draw_x, draw_y);

    for (int i = 0; i < npc_count_active; i++)
        if (npc_entities[i])
            entity_update_camera(npc_entities[i], draw_x, draw_y);
}

/*
 * Background timers (declared in timer.h; see its doc comment for the
 * "skipped, not queued" firing rule).
 */
void timer_start(int index)
{
    if (index < 0 || index >= MAX_TIMERS)
        return;

    const SceneDef *scene = scene_current();
    if (!scene || index >= scene->timer_count)
        return;

    timer_frames_left[index] = scene->timers[index].frames;
    timer_running[index] = 1;
}

static void timers_reset(void)
{
    for (int i = 0; i < MAX_TIMERS; i++)
        timer_running[i] = 0;
}

/* Ticks every armed timer down by one frame; fires whichever ones
 * reach 0 this frame, unless something else is already running (see
 * timer.h - that firing is then just skipped). Called unconditionally
 * every frame, regardless of game_state, so a timer keeps counting
 * down even through a scene transition (it just won't fire until
 * back in STATE_PLAY with nothing else active). */
static void timers_update(void)
{
    const SceneDef *scene = scene_current();
    if (!scene)
        return;

    int can_fire = (game_state == STATE_PLAY) &&
                   !script_active() && !dialogue_active();

    int n = scene->timer_count;
    if (n > MAX_TIMERS)
        n = MAX_TIMERS;

    for (int i = 0; i < n; i++)
    {
        if (!timer_running[i])
            continue;

        if (timer_frames_left[i] > 0)
        {
            timer_frames_left[i]--;
            continue;
        }

        timer_running[i] = 0;

        if (can_fire)
            script_start(scene->timers[i].script);
        /* else: this firing is simply skipped - see timer.h. */
    }
}

/* Find a scene's slot in scenes[], for saving. */
static int scene_to_index(const SceneDef *target)
{
    for (int i = 0; i < SCENE_COUNT; i++)
        if (scenes[i] == target)
            return i;

    return 0;
}

/* Builds a SaveData from however things stand right now and writes it. */
static void save_game(Entity *player)
{
    (void)player;
    game_save_slot(0);
    audio_play_save();
}

/*
 * One item name per dialogue "page" (dialogue_update() advances on
 * '\n', see dialogue.c) - the pause menu's ITEMS option just calls
 * dialogue_show(build_items_text()). Static buffer: dialogue_show()
 * only holds a pointer, so this has to outlive the call, and it's
 * about to become the box's only content.
 */
#define ITEMS_TEXT_MAX 256
static char items_text[ITEMS_TEXT_MAX];

static const char *build_items_text(void)
{
    int pos = 0;
    int have_any = 0;

    for (int i = 0; i < ITEM_COUNT && pos < ITEMS_TEXT_MAX - 2; i++)
    {
        if (!item_has(i))
            continue;

        const char *name = item_names[i];

        for (int j = 0; name[j] != 0 && pos < ITEMS_TEXT_MAX - 2; j++)
            items_text[pos++] = name[j];

        items_text[pos++] = '\n';
        have_any = 1;
    }

    if (have_any)
    {
        /* Drop the trailing '\n' so the last page isn't blank. */
        pos--;
    }
    else
    {
        static const char *none = "You don't have any items yet.";

        for (int j = 0; none[j] != 0 && pos < ITEMS_TEXT_MAX - 1; j++)
            items_text[pos++] = none[j];
    }

    items_text[pos] = 0;
    return items_text;
}


/*
 * Pick which way the player faces.
 *
 * A direction pressed this frame wins (so tapping a new direction
 * turns you right away). Otherwise keep facing the same way while
 * that button is still held, else face whatever is held.
 */
static Direction choose_direction(
    Direction current
)
{
    if (input_pressed(INPUT_UP))    return DIR_UP;
    if (input_pressed(INPUT_DOWN))  return DIR_DOWN;
    if (input_pressed(INPUT_LEFT))  return DIR_LEFT;
    if (input_pressed(INPUT_RIGHT)) return DIR_RIGHT;

    static const uint16_t dir_key[4] =
    {
        INPUT_DOWN, INPUT_UP, INPUT_RIGHT, INPUT_LEFT
    };

    if (input_held(dir_key[current]))
        return current;

    if (input_held(INPUT_UP))    return DIR_UP;
    if (input_held(INPUT_DOWN))  return DIR_DOWN;
    if (input_held(INPUT_LEFT))  return DIR_LEFT;
    if (input_held(INPUT_RIGHT)) return DIR_RIGHT;

    return current;
}


int main(void)
{
    irqInit();
    irqEnable(IRQ_VBLANK);

    /*
     * Mode 0, BG0 (scene) + BG1 (dialogue/menu box) on, hardware
     * sprites on, 1D sprite tile mapping.
     */
    REG_DISPCNT =
        MODE_0 |
        BG0_ENABLE |
        OBJ_ENABLE |
        OBJ_1D_MAP;

    input_init();
    sprite_system_init();
    background_init();
    camera_init();
    collision_init();
    entity_system_init();
    dialogue_init();
    debug_init();
    audio_init();
    music_init();

    setup_player_palette();

    /*
     * Dev/testing reset: hold SELECT + L + R at boot to skip loading
     * any existing save and start a brand-new game (clears flags/
     * inventory too, since those live in the save). This doesn't
     * touch SRAM by itself - the wipe only becomes permanent once
     * you actually save again from the pause menu.
     */
    int reset_requested =
        (~REG_KEYINPUT & (INPUT_SELECT | INPUT_L | INPUT_R)) ==
        (INPUT_SELECT | INPUT_L | INPUT_R);

    /* Resume from a save if there is one; otherwise start fresh. */
    SaveData save;
    int has_save = reset_requested ? 0 : save_read(&save);

    state_init(has_save ? save.flags : 0,
               has_save ? save.inventory : 0,
               has_save ? save.variables : 0);

    const SceneDef *scene =
        has_save ? scenes[save.scene_index] : SCENE_START;

    scene_load(scene);

    /* NPCs are spawned below, AFTER the player - see scene_sprite_mark. */

    /* Player entity using your sprite sheet, at the scene's spawn
     * (or the saved position, if we're resuming). */
    Entity *player =
        entity_create(
            ENTITY_PLAYER,
            has_save ? save.player_x : scene->player_x,
            has_save ? save.player_y : scene->player_y,
            16,
            16
        );

    if (player == 0)
    {
        while (1)
            VBlankIntrWait();
    }

    /* Lets actor_*() (and sync_camera()) target the player the same
     * way they target an NPC - see entity_for_actor()/actor.h's
     * PLAYER_ACTOR_INDEX above. */
    g_player = player;

    if (has_save)
        player->direction = save.player_direction;
    else
        player->direction = scene->player_start_direction;

    entity_set_sprite(player, &sprite_defs[player_sprite_index], PLAYER_PALETTE);

    /* The player lives for the whole game; everything allocated after
     * this point belongs to the current scene and is released on every
     * scene change (scene_entities_load() rewinds to this mark). */
    scene_sprite_mark = sprite_alloc_mark();
    scene_sprite_marked = 1;

    scene_entities_load(scene);

    /* Auto-run this scene's on_init script, if it has one - same as
     * every later scene entry (see the STATE_FADE_IN case below).
     * No fade plays at boot, so this just starts running right away;
     * the main loop's first STATE_PLAY iteration picks it up. */
    script_start(scene->on_init);

    camera_follow(
        player->x + player->width / 2,
        player->y + player->height / 2
    );

    entity_update_camera(
        player,
        camera_get_x(),
        camera_get_y()
    );

    play_scene_music(scene);

    while (1)
    {
        VBlankIntrWait();

        music_update();
        audio_update();
        input_update();
        transition_update();
        timers_update();

        /* Dev HUD: hold SELECT and press A to toggle. Checked here,
         * outside the state machine, so it works no matter what else
         * is going on (walking, dialogue, a running script). */
        if (input_held(INPUT_SELECT) && input_pressed(INPUT_A))
            debug_toggle();

        switch (game_state)
        {
        case STATE_PLAY:
        {
            /* While a dialogue box is open, only dialogue reads
             * input - the player stands still. Still synced every
             * frame in case a camera lock/pan from just before the
             * box opened is still catching up. */
            if (dialogue_active())
            {
                sync_camera(player);
                dialogue_update();
                script_update();
                if (script_wants_scene_switch(&pending_switch_scene, &pending_switch_x,
                                              &pending_switch_y, &pending_switch_dir))
                {
                    transition_fade_out();
                    game_state = STATE_FADE_OUT;
                }
                break;
            }

            /* A script is running (an NPC's on_interact, a trigger's
             * on_enter, ...) - let it run until it either pauses on
             * dialogue (handled above, next frame) or finishes. Synced
             * after script_update() so an actor move/camera pan that
             * just happened this frame is reflected immediately. */
            if (script_active())
            {
                script_update();
                sync_camera(player);

                if (script_wants_scene_switch(
                        &pending_switch_scene,
                        &pending_switch_x,
                        &pending_switch_y,
                        &pending_switch_dir))
                {
                    transition_fade_out();
                    game_state = STATE_FADE_OUT;
                }

                break;
            }

            /* Background threads keep running during normal play. */
            script_update();
            if (script_wants_scene_switch(&pending_switch_scene, &pending_switch_x,
                                          &pending_switch_y, &pending_switch_dir))
            {
                transition_fade_out();
                game_state = STATE_FADE_OUT;
                break;
            }

            /* "Attach Script To Button" scripts. */
            if (script_check_input())
                break;

            /* START: open the pause menu. */
            if (input_pressed(INPUT_START) && !script_input_overridden(INPUT_START))
            {
                menu_open();
                game_state = STATE_MENU;
                break;
            }

            int dx = 0;
            int dy = 0;

            if (input_held(INPUT_LEFT))  dx -= PLAYER_SPEED;
            if (input_held(INPUT_RIGHT)) dx += PLAYER_SPEED;
            if (input_held(INPUT_UP))    dy -= PLAYER_SPEED;
            if (input_held(INPUT_DOWN))  dy += PLAYER_SPEED;

            /*
             * Test each axis on its own so the player slides along
             * walls when moving diagonally instead of sticking.
             * Also block against solid NPCs.
             */
            int moved = 0;

            if (dx != 0 &&
                player_can_move(player, player->x + dx, player->y))
            {
                player->x += dx;
                moved = 1;
            }

            if (dy != 0 &&
                player_can_move(player, player->x, player->y + dy))
            {
                player->y += dy;
                moved = 1;
            }

            /* Facing + walk cycle. */
            entity_animate(
                player,
                choose_direction((Direction)player->direction),
                moved
            );

            /* Wander, then sync the camera (follows the player by
             * default, or whatever a script has it locked to - see
             * sync_camera()) and reposition everyone relative to it. */
            for (int i = 0; i < npc_count_active; i++)
            {
                if (npc_entities[i])
                {
                    /* Hidden actors (actor_set_visible(i, 0)) stand
                     * still, not shuffling around off-screen while
                     * they're "not there". */
                    if (npc_defs[i]->movement && npc_entities[i]->solid)
                        update_wandering_npc(i);
                }
            }

            sync_camera(player);

            /* A button: talk to whatever NPC is in front of you.
             * (SELECT+A is the debug HUD toggle above, not a talk.) */
            if (input_pressed(INPUT_A) && !input_held(INPUT_SELECT) &&
                !script_input_overridden(INPUT_A))
            {
                const ScriptEvent *script = check_npc_interact(player);

                if (script)
                {
                    script_start(script);
                    break;
                }
            }

            /* Check for trigger zones ("doors"). Edge-triggered - see
             * door_last_entered's doc comment above - so only fires on
             * the frame the player steps into the zone, not every frame
             * they keep standing in it. */
            const DoorDef *door = scene_check_doors(
                player->x, player->y,
                player->width, player->height
            );

            if (door && door != door_last_entered)
                script_start(door->on_enter);

            door_last_entered = door;

            break;
        }

        case STATE_MENU:
        {
            MenuAction action = menu_update();

            if (action == MENU_SAVE)
            {
                save_game(player);
                dialogue_show("Game saved!");
                game_state = STATE_PLAY;   /* dialogue_active() takes it from here */
            }
            else if (action == MENU_ITEMS)
            {
                dialogue_show(build_items_text());
                game_state = STATE_PLAY;   /* dialogue_active() takes it from here */
            }
            else if (action == MENU_CLOSE)
            {
                game_state = STATE_PLAY;
            }
            break;
        }

        case STATE_FADE_OUT:
            if (!transition_active())
                game_state = STATE_LOADING;
            break;

        case STATE_LOADING:
        {
            /* Load the target scene. */
            const SceneDef *next = scenes[pending_switch_scene];
            scene_load(next);
            scene_entities_load(next);
            play_scene_music(next);

            /* A camera lock or an armed timer from the scene just
             * left means nothing here - the actor index/timer slot it
             * pointed at belongs to a TimerDef/NPC array that's gone
             * now. Fresh scene, fresh camera and timers. */
            camera_release();
            timers_reset();
            script_reset_scene();
            door_last_entered = 0; /* fresh scene - no stale doors[] pointer */

            /* Move player to the target spawn. */
            player->x = pending_switch_x;
            player->y = pending_switch_y;
            if (pending_switch_dir >= 0)
                entity_animate(player, (Direction)(pending_switch_dir & 3), 0);

            camera_follow(
                player->x + player->width / 2,
                player->y + player->height / 2
            );

            entity_update_camera(
                player,
                camera_get_x(),
                camera_get_y()
            );

            transition_fade_in();
            game_state = STATE_FADE_IN;
            break;
        }

        case STATE_FADE_IN:
            if (!transition_active())
            {
                /* Auto-run the new scene's on_init script, if it has
                 * one, right as the player regains control - see
                 * "on_init" in scene JSON / scene.h. script_start(0)
                 * is a safe no-op when it doesn't. */
                script_start(scene_current()->on_init);
                game_state = STATE_PLAY;
            }
            break;
        }

        /* Runs after the state machine so it wins if dialogue/menu
         * just turned BG1 off this same frame. Rows 0-3 only, so it
         * never collides with the dialogue/menu box in rows 16-19. */
        debug_update(scene_current(), player, state_flags(), state_inventory());

        if (debug_active())
            REG_DISPCNT |= BG1_ENABLE;
    }

    return 0;
}
