#include <stdint.h>
#include <maxmod.h>

#include "music.h"          /* also pulls in soundbank.h (MOD_* ids)
                              and uge_songs.h (UGE_* ids) */
#include "soundbank_bin.h"  /* generated by the Makefile's bin2o rule -
                              declares the soundbank_bin[] data array
                              mmInitDefault needs */
#include "huge.h"
#include "script.h"

#define MUSIC_CHANNELS 8   /* simultaneous samples Maxmod can mix */

/*
 * Maxmod plays modules through the GBA's two DMA "Direct Sound"
 * channels (A/B), driven by a hardware timer - separate from the
 * PSG channel 1 blips in audio.c. mmInitDefault() is supposed to
 * turn these on itself, but audio_init() runs first and writes
 * REG_SOUNDCNT_H with only the PSG bits set (DMA A/B left off), so
 * we re-assert the DMA-enable bits here right after Maxmod's own
 * init, as a defensive belt-and-suspenders measure in case
 * anything in that ordering leaves them off.
 */
#define REG_SOUNDCNT_H (*(volatile uint16_t *)0x04000082)

/* GB NR50/NR51 (master volume / channel panning), which .uge songs
 * drive directly - see huge.c. */
#define REG_NR50 (*(volatile uint8_t *)0x04000080)
#define REG_NR51 (*(volatile uint8_t *)0x04000081)

void music_init(void)
{
    mmInitDefault((mm_addr)soundbank_bin, MUSIC_CHANNELS);

    REG_SOUNDCNT_H =
        0x0002 |        /* PSG channels at 100% (keep audio.c's blips as-is) */
        (1 << 2)  |     /* DMA Sound A: 100% volume */
        (1 << 8)  |     /* DMA Sound A -> right speaker */
        (1 << 9)  |     /* DMA Sound A -> left speaker */
        (0 << 10) |     /* DMA Sound A: use Timer 0 */
        (1 << 11) |     /* DMA Sound A: reset FIFO */
        (1 << 3)  |     /* DMA Sound B: 100% volume */
        (1 << 12) |     /* DMA Sound B -> right speaker */
        (1 << 13) |     /* DMA Sound B -> left speaker */
        (0 << 14) |     /* DMA Sound B: use Timer 0 */
        (1 << 15);      /* DMA Sound B: reset FIFO */
}

/* See music_current_track()'s doc comment in music.h. */
static int current_track = -1;

/* Which player owns current_track, and whether a .uge track loops
 * (Maxmod handles MM_PLAY_ONCE itself). */
static int uge_playing;
static int uge_loop;

/* Per PSG channel: frames left before a sound effect gives the channel
 * back to the song (see music_sfx_claim_channel), and channels muted by
 * the "Mute Channel" script event. A channel is muted in the driver
 * while either applies. */
static int sfx_frames[4];
static uint8_t user_mute_mask;

/* "Set Music Routine" scripts, run when a song plays effect 6xx. */
static const ScriptEvent *routine_scripts[16];

static int is_uge_track(int track_id)
{
    return track_id >= MUSIC_UGE_BASE
        && track_id < MUSIC_UGE_BASE + UGE_SONG_COUNT;
}

static int channel_muted(int ch)
{
    return sfx_frames[ch] > 0 || ((user_mute_mask >> ch) & 1);
}

static void apply_mutes(void)
{
    for (int ch = 0; ch < 4; ch++)
        huge_mute_channel((uint8_t)ch, (uint8_t)channel_muted(ch));
}

static void stop_uge(void)
{
    if (!uge_playing)
        return;
    uge_playing = 0;
    huge_silence();
}

static void on_routine(uint8_t routine)
{
    if (routine_scripts[routine])
        script_thread_start(routine_scripts[routine]);
}

void music_update(void)
{
    /* Standard GBA Maxmod API: the tracker's timing is driven by
     * this once-per-vblank call, not a separate frame-poll function. */
    mmVBlank();

    for (int ch = 0; ch < 4; ch++)
    {
        if (sfx_frames[ch] > 0 && --sfx_frames[ch] == 0 && uge_playing && !channel_muted(ch))
            huge_mute_channel((uint8_t)ch, 0);
    }

    if (uge_playing) {
        /* GB Studio ticks hUGEDriver once per Game Boy vblank; the
         * GBA's vblank runs at the same ~59.7 Hz, so tempo matches. */
        huge_dosound();
        if (!uge_loop && huge_song_wrapped())
            music_stop();
    }
}

void music_play(int track_id, int loop)
{
    if (is_uge_track(track_id)) {
        mmStop();
        stop_uge();

        /* Everything on, all four channels to both speakers - the
         * song's own 5xx/8xx effects can change these as it plays. */
        REG_NR50 = 0x77;
        REG_NR51 = 0xFF;

        huge_set_routine_callback(on_routine);
        huge_init(uge_songs[track_id - MUSIC_UGE_BASE]);
        apply_mutes();      /* huge_init() clears the driver's mutes */
        uge_playing = 1;
        uge_loop = loop;
    } else {
        stop_uge();
        mmStart(track_id, loop ? MM_PLAY_LOOP : MM_PLAY_ONCE);
    }
    current_track = track_id;
}

void music_stop(void)
{
    mmStop();
    stop_uge();
    current_track = -1;
}

int music_current_track(void)
{
    return current_track;
}

void music_sfx_claim_channel(int ch, int frames)
{
    if (ch < 0 || ch > 3)
        return;
    if (uge_playing && !channel_muted(ch))
        huge_mute_channel((uint8_t)ch, 1);
    if (frames > sfx_frames[ch])
        sfx_frames[ch] = frames;
}

void music_sfx_claim_channel1(int frames)
{
    music_sfx_claim_channel(0, frames);
}

void music_set_channel_muted(int ch, int muted)
{
    if (ch < 0 || ch > 3)
        return;
    if (muted)
        user_mute_mask |= (uint8_t)(1 << ch);
    else
        user_mute_mask &= (uint8_t)~(1 << ch);
    if (uge_playing)
        huge_mute_channel((uint8_t)ch, (uint8_t)channel_muted(ch));
}

void music_set_routine(int routine, const ScriptEvent *script)
{
    if (routine >= 0 && routine < 16)
        routine_scripts[routine] = script;
}
