"""
Generates engine/data/font_data.c/h - an 8x8 pixel font for the
dialogue box, covering ASCII 32-126 (space through ~).

Rasterizes DejaVu Sans Mono Bold at a tiny size and thresholds to
1-bit, then packs as GBA 4bpp tiles using a 2-color palette:

    index 0  unused (never appears in a tile - keeps every dialogue
             tile fully opaque, since BG palette index 0 is the
             hardware's "see-through to the layer behind" color)
    index 1  box background fill
    index 2  text (foreground)

Run manually if you want to change the font colors or source font:

    python tools/gen_font.py
"""

from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FONT_PATH = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
FIRST_CHAR = 32
LAST_CHAR = 126
GLYPH_COUNT = LAST_CHAR - FIRST_CHAR + 1

# Box fill (dark blue-black) and text (near-white) as GBA BGR555.
BOX_COLOR  = (16, 16, 32)
TEXT_COLOR = (248, 248, 248)


def gba5(v):
    return (v * 31 + 127) // 255


def gba_color(rgb):
    r, g, b = rgb
    return gba5(r) | (gba5(g) << 5) | (gba5(b) << 10)


def render_glyph(font, ch):
    img = Image.new("L", (8, 8), 0)
    d = ImageDraw.Draw(img)
    d.text((0, -1), ch, font=font, fill=255)
    return img


def glyph_to_tile(img):
    """8x8 1-bit glyph -> 32 bytes of 4bpp GBA tile data (index 1 or 2)."""
    pixels = []
    for y in range(8):
        for x in range(8):
            v = img.getpixel((x, y))
            pixels.append(2 if v > 120 else 1)

    out = []
    for i in range(0, 64, 2):
        out.append(pixels[i] | (pixels[i + 1] << 4))
    return out


def format_bytes(data, per_line=16):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(lines)


def main():
    here = Path(__file__).resolve().parent
    out_dir = here.parent / "engine" / "data"
    out_dir.mkdir(parents=True, exist_ok=True)

    font = ImageFont.truetype(FONT_PATH, 8)

    tile_bytes = []
    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        img = render_glyph(font, chr(code))
        tile_bytes.extend(glyph_to_tile(img))

    palette = [0, gba_color(BOX_COLOR), gba_color(TEXT_COLOR)] + [0] * 13

    c_lines = [
        "/*",
        " * Generated by tools/gen_font.py - do not edit.",
        " */",
        "",
        "#include <stdint.h>",
        "",
        '#include "font_data.h"',
        "",
        f"const uint8_t font_tiles[{len(tile_bytes)}] __attribute__((aligned(4))) =",
        "{",
        format_bytes(tile_bytes),
        "};",
        "",
        "const uint16_t font_palette[16] __attribute__((aligned(4))) =",
        "{",
        "    " + ", ".join(f"0x{c:04X}" for c in palette) + ",",
        "};",
        "",
    ]
    (out_dir / "font_data.c").write_text("\n".join(c_lines), encoding="utf-8")

    h_lines = [
        "/*",
        " * Generated by tools/gen_font.py - do not edit.",
        " */",
        "",
        "#ifndef FONT_DATA_H",
        "#define FONT_DATA_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define FONT_FIRST_CHAR {FIRST_CHAR}",
        f"#define FONT_LAST_CHAR  {LAST_CHAR}",
        f"#define FONT_GLYPH_COUNT {GLYPH_COUNT}",
        "",
        f"extern const uint8_t  font_tiles[{len(tile_bytes)}];",
        "extern const uint16_t font_palette[16];",
        "",
        "#endif",
        "",
    ]
    (out_dir / "font_data.h").write_text("\n".join(h_lines), encoding="utf-8")

    print(f"Wrote {out_dir / 'font_data.c'} ({GLYPH_COUNT} glyphs, "
          f"{len(tile_bytes)} bytes)")


if __name__ == "__main__":
    main()
