from PIL import Image
from pathlib import Path
import sys


FRAME_W = 16
FRAME_H = 16


def gba5(value):
    return (value * 31 + 127) // 255


def gba_color(r, g, b):
    return (
        gba5(r)
        | (gba5(g) << 5)
        | (gba5(b) << 10)
    )


def build_palette(image):
    colors = []

    for r, g, b, a in image.getdata():

        if a == 0:
            continue

        color = (r, g, b)

        if color not in colors:
            colors.append(color)

    if len(colors) > 15:
        raise ValueError(
            f"Sprite has {len(colors)} visible colors. "
            "Maximum is 15."
        )

    palette = [(0, 0, 0, 0)]

    for color in colors:
        palette.append(
            (*color, 255)
        )

    return palette


def pixel_index(pixel, palette):

    r, g, b, a = pixel

    if a == 0:
        return 0

    return palette.index(
        (r, g, b, 255)
    )


def convert_8x8(tile, palette):

    pixels = []

    for y in range(8):
        for x in range(8):

            pixels.append(
                pixel_index(
                    tile.getpixel((x, y)),
                    palette
                )
            )

    result = []

    for i in range(0, 64, 2):

        result.append(
            pixels[i]
            | (pixels[i + 1] << 4)
        )

    return result


def convert_frame(frame, palette):

    data = []

    # GBA 1D OBJ layout:
    #
    # 0 1
    # 2 3

    for ty in range(2):

        for tx in range(2):

            tile = frame.crop(
                (
                    tx * 8,
                    ty * 8,
                    tx * 8 + 8,
                    ty * 8 + 8
                )
            )

            data.extend(
                convert_8x8(
                    tile,
                    palette
                )
            )

    return data


def format_array(data):

    lines = []

    for i in range(0, len(data), 16):

        chunk = data[i:i + 16]

        lines.append(
            "    "
            + ", ".join(
                f"0x{x:02X}"
                for x in chunk
            )
            + ","
        )

    return "\n".join(lines)


def main():

    if len(sys.argv) != 3:

        print(
            "Usage:"
        )

        print(
            "python png_to_gba_sprite.py "
            "input.png output.c"
        )

        return 1

    input_file = Path(sys.argv[1])
    output_file = Path(sys.argv[2])

    print(
        f"Loading {input_file}"
    )

    image = Image.open(
        input_file
    ).convert("RGBA")

    print(
        f"Image size: {image.width}x{image.height}"
    )

    if image.size != (96, 16):

        raise ValueError(
            "Expected a 96x16 sprite sheet."
        )

    palette = build_palette(
        image
    )

    print(
        f"Visible colors: {len(palette) - 1}"
    )

    frames = []

    # Original frames:
    #
    # 0 Down 1
    # 1 Down 2
    # 2 Up 1
    # 3 Up 2
    # 4 Right 1
    # 5 Right 2

    for i in range(6):

        frame = image.crop(
            (
                i * FRAME_W,
                0,
                (i + 1) * FRAME_W,
                FRAME_H
            )
        )

        frames.append(frame)

    # Generate left frames.

    frames.append(
        frames[5].transpose(
            Image.Transpose.FLIP_LEFT_RIGHT
        )
    )

    frames.append(
        frames[4].transpose(
            Image.Transpose.FLIP_LEFT_RIGHT
        )
    )

    print(
        "Generating 8 animation frames..."
    )

    sprite_data = []

    for frame in frames:

        sprite_data.extend(
            convert_frame(
                frame,
                palette
            )
        )

    gba_palette = []

    for r, g, b, a in palette:

        if a == 0:
            gba_palette.append(0)

        else:
            gba_palette.append(
                gba_color(r, g, b)
            )

    while len(gba_palette) < 16:
        gba_palette.append(0)

    output = []

    output.append(
        "/*"
    )

    output.append(
        " * Generated by "
        "png_to_gba_sprite.py"
    )

    output.append(
        " */"
    )

    output.append("")

    output.append(
        "#include <stdint.h>"
    )

    output.append("")

    output.append(
        "#define PLAYER_FRAME_COUNT 8"
    )

    output.append(
        "#define PLAYER_FRAME_SIZE 128"
    )

    output.append("")

    output.append(
        "const uint8_t player_graphics[] ="
    )

    output.append("{")

    output.append(
        format_array(
            sprite_data
        )
    )

    output.append("};")

    output.append("")

    output.append(
        "const uint16_t player_palette[16] ="
    )

    output.append("{"
    )

    output.append(
        "    "
        + ", ".join(
            f"0x{x:04X}"
            for x in gba_palette
        )
        + ","
    )

    output.append(
        "};"
    )

    output.append("")

    output.append(
        "const uint32_t "
        "player_frame_offsets[8] ="
    )

    output.append("{")

    output.append(
        "    0, 128, 256, 384, "
        "512, 640, 768, 896,"
    )

    output.append(
        "};"
    )

    output.append("")

    output_file.write_text(
        "\n".join(output),
        encoding="utf-8"
    )

    print(
        f"Generated {output_file}"
    )

    # Matching header so engine code can use the data.
    header_file = output_file.with_suffix(".h")

    guard = (
        header_file.stem.upper()
        + "_H"
    )

    header = [
        "/*",
        " * Generated by png_to_gba_sprite.py",
        " */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
        "#define PLAYER_FRAME_COUNT 8",
        "#define PLAYER_FRAME_SIZE 128",
        "",
        "extern const uint8_t player_graphics[];",
        "extern const uint16_t player_palette[16];",
        "extern const uint32_t player_frame_offsets[8];",
        "",
        "#endif",
        "",
    ]

    header_file.write_text(
        "\n".join(header),
        encoding="utf-8"
    )

    print(
        f"Generated {header_file}"
    )

    print("")
    print("Animation layout:")
    print("  Frame 0 = Down 1")
    print("  Frame 1 = Down 2")
    print("  Frame 2 = Up 1")
    print("  Frame 3 = Up 2")
    print("  Frame 4 = Right 1")
    print("  Frame 5 = Right 2")
    print("  Frame 6 = Left 1")
    print("  Frame 7 = Left 2")

    return 0


if __name__ == "__main__":
    sys.exit(main())

